[project]
name = "telewish"
version = "1.0.0"
description = "Your minimalistic wish-list with a friendly tg-bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-tailwind[reload]>=4.0.1",
    "django>=5.2",
    "pillow>=11.1.0",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.0.1",
    "cookiecutter>=2.6.0",
]

[tool.uv]
default-groups = ["test"]

[dependency-groups]
test = [
    "pytest>=8.3.4",
    "pytest-django>=4.10.0",
]

[tool.mypy]
ignore_missing_imports = true
